### PR TITLE
apply patch:  force-persistent-buffers

### PR DESCRIPTION
**Pull request by ghost**
Consider merging this patch to prevent possible graphical glitches on the SolidRun HoneyComb LX2K with an AMDGPU card.

This patch didn't make it into upstream mesa: https://gitlab.freedesktop.org/mesa/mesa/-/issues/3274

### CODE REVIEW

**Comment by aleasto** [comment]
What is the source of the patch? I don't see it in the linked issue

**Comment by ghost** [comment]
> What is the source of the patch? I don't see it in the linked issue


https://github.com/HanoJing/android_external_mesa3d/blob/lineage-18.1/0001-radeonsi-On-Aarch64-force-persistent-buffers-to-GTT.patch

I'm not the creator of the patch. Jon Nettleton is the creator of the issue and the patch.

**Comment by aleasto** [comment]
I can see who's the author, but where was the patch first posted? Where did you take it from?

**Comment by ghost** [comment]
> I can see who's the author, but where was the patch first posted? Where did you take it from?

Ooh. Then this might be what you're looking for:
https://gist.github.com/jnettlet/4dd6e43bcd5a551df29b12d3212e6edd

**Comment by aleasto** [comment]
Pushed

**Pull request closed without merging**
